### ISSUE TITLE
Upgrade documentation to ascii-doc

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-c4corpus#12]
Similar to dkpro-tc or dkpro-core would be nice, if the documentation grows in the future.

**Comment by habernal** [comment]
Link to generated doc at Jenkins is not public - @reckart any thoughts how to fix that?

**Comment by reckart** [comment]
Check out http://dkpro.github.io/developer/asciidoc-build-in-jenkins/ - in particular the second part under "Publishing the documentation".

**Comment by habernal** [comment]
Closing for now; ascii doc working, linked, and publicly accessible.
