### ISSUE TITLE
Consistent naming of output folders to match input CommonCrawl

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-c4corpus#18]
The 2015-11 output was actually performed on CC-MAIN-2015-27, so we need to
- [x] rename output folders in the S3 bucked
- [x] update the readme appropriately

**Comment by tfmorris** [comment]
Is the 2015-11 directory output different than what is described in the paper? The paper says "November 2015" and the number of files and total size match those for the CC-MAIN-2015-48 crawl.

**Comment by habernal** [comment]
Correct, this is s3://aws-publicdatasets/common-crawl/crawl-data/CC-MAIN-2015-48/. No idea, where did I get the "CC-MAIN-2015-27"...

**Comment by tfmorris** [comment]
Phew! That's a relief. :-)

**Comment by habernal** [comment]
Moving files to new location using S3 cmd:

```
user-ukp@DIPF-UKP-IH-NB1:~$ aws s3 mv s3://ukp-research-data/c4corpus/cc-final-2015-11/ s3://ukp-research-data/c4corpus/CC-MAIN-2015-48/cc-final-2015-48/ --recursive
```

test with --dryrun first

**Comment by habernal** [comment]
LREC C4Corpus moved to s3://ukp-research-data/c4corpus/CC-MAIN-2015-48/cc-final-2015-48/
- cleaned intermediate data
- ran first several phases on 2016-07 and moved to appropriate directory as well

**Comment by tfmorris** [comment]
Bummer! I was just in the middle of collecting samples of the intermediary files to help understand the algorithm. :-(

The new names should make it easier for folks to understand what was derived from what though. :-)

A couple of anomalies that I noticed:
- CC-MAIN-2015-48/cc-phase2out-2016-07 looks wrong to me 
- cc-phase2-step1-out-2016-07 and cc-phase3step1out-2016-07 are at the top level when they should presumably it should be in CC-MAIN-2016-07/

**Comment by habernal** [comment]
Oops, sorry, Tom.
- CC-MAIN-2015-48/cc-phase2out-2016-07 looks wrong to me
  - my bad, moved wrongly to 2015-48, now moving to the correct one (2016-07)
- cc-phase2-step1-out-2016-07 and cc-phase3step1out-2016-07 are at the top level when they should presumably it should be in CC-MAIN-2016-07/
  - yes, started moving these; it takes some time with aws s3 cmd though

I've also cleaned some intermediate steps for 2015-48 as they are not important (as a final product) and just occupy s3.
