### ISSUE TITLE
Fix javadoc for Java 1.8

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-c4corpus#24]
Java 1.8 is quite strict and picky about missing javadoc entries.

**Comment by reckart** [comment]
Note: there are JavaDoc warnings and errors and if you don't look closely, you might confuse an "error" at the Maven log level for a "warning" at the javadoc level just after.

So search for `: error:` to find the actual JavaDoc errors. Typically these are malformed HTML, not missing descriptions!
