### ISSUE TITLE
Deploy release to Maven Central

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-c4corpus#3]
As a part of releasing 1.0 version
- deploy to Maven repository (important for, i.e., boilerplate rem.)

**Comment by habernal** [comment]
Deployed; currently staging; needs to try out later once mirrored to mvncentral.

**Comment by reckart** [comment]
@habernal normally you test against the staged repository and only when you are happy, then you promote to maven central

**Comment by reckart** [comment]
#32 must be cleared before release. The presently staged release should be dropped.

**Comment by habernal** [comment]
Version 1.0.0 released on maven central.
