### ISSUE TITLE
Improve CleanEval reproducibility documentation

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-c4corpus#4]
To make sure everything in /de.tudarmstadt.ukp.dkpro.c4corpus.boilerplate/ for CleanEval running is correct and can be run without additional tweaking

**Comment by habernal** [comment]
File 103.txt in gold standard CleanEval was corrupted even in the official distribution. Deleted.

**Comment by tfmorris** [comment]
If you're not going to mirror the CleanEval HTML input (http://cleaneval.sigwac.org.uk/finalrun-input.tar.gz), you should probably at least provide a link to it. Even better would be a script or set of scripts that download & unpacks the HTML, runs the boilerplate on it, evaluates the results against the gold standard.

Other useful links:
- the Python JusText implementation that you evaluated against (there are a few different repos on Google Code, Github, etc to choose from and code changes over time)
- the main CleanEval site
- other related repos like https://github.com/ppke-nlpg/boilerplateResults/tree/master/cleanEvalResults

**Comment by OmniaZayed** [comment]
Done via [b170534](https://github.com/dkpro/dkpro-c4corpus/commit/b170534b0ff8e61abe174e798c6cbbfcfe763ace)
