### ISSUE TITLE
Extract WARC records given a list of URLs

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro-c4corpus#43]
For a feasible list of URLs (max hunderds of thousands) given as a parameter.

**Comment by tfmorris** [comment]
For small numbers of URLs, using the CommonCrawl URL index may be most efficient. For larger numbers, inverting the deduping strategy should allow the URL list to be basically unbounded. ie map both URL list and text WARCs using URL as key (and dummy WARCRecord for URL list), then in the reducers.

**Comment by habernal** [comment]
Yes, for large set of URLs a side-reduce join would do the job at best. Though, so far we have a use case for a small list of URLs, so I'd leave it as a shared-memory parameter for now. The CommonCrawl URL index works fine, but this solution can run ad-hoc on any arbitrary *.warc.gz collection (in this case C4Corpus, for example).

**Comment by habernal** [comment]
Commit d4a492e

**Comment by habernal** [comment]
Was failing with `java.lang.IllegalArgumentException: Wrong FS: s3://ukp-research-data/xxx.txt, expected: hdfs://ip-172-31-12-117.ec2.internal:8020` due to direct reading from FileInputStream
